# Basic Setup And Data Import

In [ ]:
import pandas as pd
import numpy as np

## Data Importation

In [ ]:
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

In [ ]:
file1 = "/content/drive/Shareddrives/CIS5500: Databases Project/Data/species.csv"
file2 = "/content/drive/Shareddrives/CIS5500: Databases Project/Data/AllTrails data - nationalpark.csv"
file3 = "/content/drive/Shareddrives/CIS5500: Databases Project/Data/parks.csv"
file4 = "/content/drive/Shareddrives/CIS5500: Databases Project/Data/airbnb_listings_usa.csv"

In [ ]:
species = pd.read_csv(file1)
trails = pd.read_csv(file2)
parks = pd.read_csv(file3)
airbnb = pd.read_csv(file4)

<ipython-input-43-95ea9d42eb18>:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  species = pd.read_csv(file1)
<ipython-input-43-95ea9d42eb18>:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb = pd.read_csv(file4)

# Initial Data Exploration

In [ ]:
species.head()

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [ ]:
parks.head()

  Park Code               Park Name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

In [ ]:
trails.head()

,trail_id,name,area_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18852, 'lng': -149.63156}",24.8931,15610.598,1161.8976,5,out and back,3.0,5.0,423,"['dogs-no', 'forest', 'river', 'views', 'water...","['birding', 'camping', 'hiking', 'nature-trips...",i
1,10236086,Mount Healy Overlook Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73049, 'lng': -148.91968}",18.0311,6920.162,507.7968,3,out and back,1.0,4.5,260,"['dogs-no', 'forest', 'views', 'wild-flowers',...","['birding', 'camping', 'hiking', 'nature-trips...",i
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18879, 'lng': -149.631}",17.7821,2896.812,81.9912,1,out and back,3.0,4.5,224,"['dogs-no', 'partially-paved', 'views', 'wildl...","['hiking', 'walking']",i
3,10236076,Horseshoe Lake Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73661, 'lng': -148.915}",16.2674,3379.614,119.7864,1,loop,2.0,4.5,237,"['dogs-no', 'forest', 'lake', 'kids', 'views',...","['birding', 'hiking', 'nature-trips', 'trail-r...",i
4,10236082,Triple Lakes Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73319, 'lng': -148.89682}",12.5935,29772.790,1124.7120,5,out and back,1.0,4.5,110,"['dogs-no', 'lake', 'views', 'wild-flowers', '...","['birding', 'fishing', 'hiking', 'nature-trips...",i

In [ ]:
airbnb.head()

,Unnamed: 0,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,...,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,state,city
0,0,183319,Panoramic Ocean View Venice Beach,867995,Barbara X,City of Los Angeles,Venice,33.99211,-118.47600,Entire home/apt,...,30,3,2019-02-25,0.02,2,0,0,NaN,CA,Los Angeles
1,1,109,Amazing bright elegant condo park front *UPGRA...,521,Paolo,Other Cities,Culver City,33.98301,-118.38607,Entire home/apt,...,30,2,2016-05-15,0.01,1,139,0,NaN,CA,Los Angeles
2,2,51307,Spanish Bungalow Guest House LA CA. 30 plus ni...,235568,David,City of Los Angeles,Atwater Village,34.12206,-118.26783,Entire home/apt,...,30,138,2020-12-13,0.98,2,224,0,NaN,CA,Los Angeles
3,3,184314,Boho Chic Flat..Steps to Beach!,884031,Ashley,City of Los Angeles,Venice,33.97487,-118.46312,Entire home/apt,...,30,30,2017-12-24,0.22,1,0,0,NaN,CA,Los Angeles
4,4,51498,Guest House With Its Own Entrance/Exit and Hot...,236758,Bay,City of Los Angeles,Mar Vista,34.00389,-118.44126,Entire home/apt,...,3,378,2022-08-21,2.60,1,348,41,HSR19-001336,CA,Los Angeles

# Data Cleaning

## Formatting column names

In [ ]:
# Change column names to lower case and substitute space with "_"
species = species.rename(columns=lambda x: x.lower().replace(" ", "_"))
trails = trails.rename(columns=lambda x: x.lower().replace(" ", "_"))
parks = parks.rename(columns=lambda x: x.lower().replace(" ", "_"))
airbnb = airbnb.rename(columns=lambda x: x.lower().replace(" ", "_"))

In [ ]:
# Change column names that start with "_" in trails
trails = trails.rename(columns = {'_geoloc':'geoloc'})

In [ ]:
# Change column name of "order" to "order_name" in species dataset
species = species.rename(columns = {'order':'order_name'})

## Drop unnamed and unrelated columns

In [ ]:
# Change the column name of "area_name" to "park_name" in the trails dataset
trails = trails.rename(columns = {'area_name':'park_name'})

In [ ]:
# Drop unnamed column in airbnb
airbnb = airbnb.drop(columns = ['unnamed:_0'])
airbnb.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'state',
       'city'],
      dtype='object')

In [ ]:
# Drop unnamed column in species
species = species.drop(columns = ['unnamed:_13'])
species.columns

Index(['species_id', 'park_name', 'category', 'order_name', 'family',
       'scientific_name', 'common_names', 'record_status', 'occurrence',
       'nativeness', 'abundance', 'seasonality', 'conservation_status'],
      dtype='object')

In [ ]:
# Drop unit column in trails because all units are supposed to be in meters
trails = trails.drop(columns = ['units'])
trails.columns

Index(['trail_id', 'name', 'park_name', 'city_name', 'state_name',
       'country_name', 'geoloc', 'popularity', 'length', 'elevation_gain',
       'difficulty_rating', 'route_type', 'visitor_usage', 'avg_rating',
       'num_reviews', 'features', 'activities'],
      dtype='object')

## Drop unneeded columns

In [ ]:
# Drop unneeded columns in trails such as vistor_usage
trails = trails.drop(columns = ['visitor_usage'])
trails.columns

Index(['trail_id', 'name', 'park_name', 'city_name', 'state_name',
       'country_name', 'geoloc', 'popularity', 'length', 'elevation_gain',
       'difficulty_rating', 'route_type', 'avg_rating', 'num_reviews',
       'features', 'activities'],
      dtype='object')

## Make park names across all datasets consistent

In [ ]:
# Check how many unique national park names are in the park dataset
len(parks['park_name'].unique())

56

In [ ]:
# Check if the park names in the species dataset and in the park dataset are consistent with each other
if set(species['park_name']) == set(parks['park_name']):
    print("The park names are consistent")
else:
    print("The park names are not consistent")

The park names are consistent

In [ ]:
# Check if the park names in the trails dataset and in the park dataset are consistent with each other
if set(trails['park_name']) == set(parks['park_name']):
    print("The park names are consistent")
else:
    print("The park names are not consistent")

The park names are not consistent

In [ ]:
# Check the number of unique natioanl park names in the trails dataset
len(trails['park_name'].unique())

60

In [ ]:
# Find the park name that are not consistent between parks and trails dataset
set1 = set(parks['park_name'])
set2 = set(trails['park_name'])

diff_parks = set1.symmetric_difference(set2)
diff_parks

{'Clayton Co International Park, Jonesboro GA',
 'Congaree National Park Wilderness',
 'Denali National Park',
 'Denali National Park and Preserve',
 'Fort Hunt National Park',
 'Fort Pickens National Park',
 'Gates Of The Arctic National Park and Preserve',
 'Gateway Arch National Park',
 'Glacier Bay National Park',
 'Glacier Bay National Park and Preserve',
 'Indiana Dunes National Park',
 'Katmai National Park',
 'Katmai National Park and Preserve',
 'Kings Canyon National Park',
 'Kobuk Valley National Park',
 'Lake Clark National Park and Preserve',
 'Sequoia National Park',
 'Sequoia and Kings Canyon National Parks',
 'Wolf Trap National Park for the Performing Arts',
 'Wrangell - St Elias National Park and Preserve'}

In [ ]:
# Make the park names in trails be consistent with the ones in parks
trails['park_name'] = trails['park_name'].replace('Congaree National Park Wilderness', 'Congaree National Park')
trails['park_name'] = trails['park_name'].replace('Denali National Park', 'Denali National Park and Preserve')
trails['park_name'] = trails['park_name'].replace('Katmai National Park', 'Katmai National Park and Preserve')
trails['park_name'] = trails['park_name'].replace('Glacier Bay National Park', 'Glacier Bay National Park and Preserve')

In [ ]:
# Keep only the park names that are in the park dataset
common_parks = set(parks['park_name']).intersection(set(trails['park_name']))

trails = trails[trails['park_name'].isin(common_parks)]

In [ ]:
# Again, check the number of unique national park names in the trails dataset
len(trails['park_name'].unique())

51

In [ ]:
# Check if all the park name in trails dataset is in parks dataset
if trails['park_name'].isin(parks['park_name']).all():
    print("All park names in trails dataset are in parks dataset")
else:
    print("Some park names in trails dataset are not in parks dataset")

All park names in trails dataset are in parks dataset

In [ ]:
# Check if all the park names in the parks dataset are unique
if parks['park_name'].duplicated().any():
    print("There are duplicate park names in the parks dataset")
else:
    print("All park names in the parks dataset are unique")

All park names in the parks dataset are unique

In [ ]:
# Check if each park ID matches uniquely to a park name
unique_parks = parks[['park_code', 'park_name']].drop_duplicates()

if len(unique_parks) == len(parks):
    print("Each park ID matches uniquely to a park name")
else:
    print("There are park IDs that match to multiple park names or vice versa")

Each park ID matches uniquely to a park name

## Add Column to Trail

In [ ]:
# Add park_code column to trails
merged_df = pd.merge(trails, parks, on='park_name')
trails= merged_df[['trail_id','park_code','name','park_name','city_name','state_name','country_name','geoloc',
                   'popularity','length','elevation_gain','difficulty_rating','route_type','avg_rating', 'num_reviews','features','activities']]

## Parse Geoloc into Longitude and Latitude

In [ ]:
# Check the datatype of Geoloc

trail_id               int64
park_code             object
name                  object
park_name             object
city_name             object
state_name            object
country_name          object
geoloc                object
popularity           float64
length               float64
elevation_gain       float64
difficulty_rating      int64
route_type            object
avg_rating           float64
num_reviews            int64
features              object
activities            object
dtype: object

In [ ]:
# Convert 'geoloc' column from string to dictionary, and split into separate 'latitude' and 'longitude' columns
trails[['latitude', 'longitude']] = trails['geoloc'].apply(lambda x: pd.Series(eval(x.replace("'", '"'))) if isinstance(x, str) else pd.Series([None, None]))

# Drop the original 'geoloc' column
trails = trails.drop('geoloc', axis=1)

# Export Cleaned Data

In [ ]:
# Export cleaned dataset to csv
species.to_csv('/content/drive/Shareddrives/CIS5500: Databases Project/Data/species_cleaned.csv', index=False)
parks.to_csv('/content/drive/Shareddrives/CIS5500: Databases Project/Data/parks_cleaned.csv', index=False)
trails.to_csv('/content/drive/Shareddrives/CIS5500: Databases Project/Data/trails_cleaned.csv', index=False)
airbnb.to_csv('/content/drive/Shareddrives/CIS5500: Databases Project/Data/airbnb_cleaned.csv', index=False)